Feature ETP-2645: Changes in pipeline file to support Etendo plugin in sources

diff --git a/pipelines/unittests/JenkinsfileOracle b/pipelines/unittests/JenkinsfileOracle
--- a/pipelines/unittests/JenkinsfileOracle
+++ b/pipelines/unittests/JenkinsfileOracle
@@ -17,8 +17,12 @@ pipeline {
         LANG                = 'en_US.UTF-8'
         EMAIL_ADDRESS       = credentials('email_builds')
 
-        REPO_URL            = 'https://github.com/etendosoftware/etendo_core'
         REPO_NAME           = 'etendo_core'
+        REPO_URL            = 'https://github.com/etendosoftware/etendo_core'
+
+        CLONE_PLUGIN        = 'TRUE'
+        PLUGIN_NAME         = 'buildSrc'
+        PLUGIN_URL          = 'git@github.com:etendosoftware/com.etendoerp.gradleplugin.git'
 
         SUCCESS             = 'SUCCESS'
         FAILED              = 'FAILED'
@@ -36,92 +40,20 @@ pipeline {
         COMMIT_INPROGRESS_STATUS = 'pending'
         COMMIT_SUCCESS_STATUS    = 'success'
         COMMIT_FAILED_STATUS     = 'failure'
+
+        TRUE  = 'TRUE'
+        FALSE = 'FALSE'
+
+        JIRA_BASE_URL             = credentials('jira-url')
+        // Jenkins credential stored as base64-encoded string for another Atlassian user, not etendobot
+        JIRA_ACCESS_TOKEN         = credentials('jira-access-token')
     }
 
     agent {
         kubernetes {
             inheritFrom 'jenkins-node-unittests-orcl'
             defaultContainer 'jnlp'
-            yaml """
-apiVersion: v1
-kind: Pod
-metadata:
-  name: jenkins-node-unittests-orcl-0
-  namespace: jenkins2025
-  labels:
-    app.kubernetes.io/name: jenkins-node-unittests-orcl
-spec:
-  imagePullSecrets:
-    - name: docker-auth-config-secret
-  volumes:
-    - name: rsa-keys
-      configMap:
-        name: rsa-keys
-        defaultMode: 384
-    - name: docker-sock
-      hostPath:
-        path: /var/run/docker.sock
-        type: ''
-  containers:
-    - name: compiler
-      image: etendo/compiler_jenkins:1.0.7-jdk.17.0.13
-      ports:
-        - name: ssh
-          containerPort: 22
-          protocol: TCP
-        - name: visualvm
-          containerPort: 8000
-          protocol: TCP
-      resources:
-        limits:
-          cpu: 3072m
-          memory: 5000Mi
-        requests:
-          cpu: 3072m
-          memory: 5000Mi
-      volumeMounts:
-        - name: rsa-keys
-          mountPath: /root/.ssh/
-        - name: docker-sock
-          mountPath: /var/run/docker.sock
-      lifecycle:
-        postStart:
-          exec:
-            command:
-              - bash
-              - '-c'
-              - >-
-                chmod a+x /var/run/docker.sock && rm
-                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
-                install -y curl
-      terminationMessagePath: /dev/termination-log
-      terminationMessagePolicy: File
-      imagePullPolicy: IfNotPresent
-    - name: oracle
-      image: etendo/oracle:19.3.0-ee
-      env:
-        - name: ORACLE_PWD
-          value: oraclepassword
-        - name: ORACLE_SID
-          value: orclsid
-      ports:
-        - name: oracle
-          containerPort: 1521
-          protocol: TCP
-        - name: oracle-em
-          containerPort: 5500
-          protocol: TCP
-      resources:
-        limits:
-          cpu: 2000m
-          memory: 6000Mi
-  restartPolicy: Always
-  terminationGracePeriodSeconds: 30
-  dnsPolicy: ClusterFirst
-  serviceAccountName: default
-  serviceAccount: default
-  securityContext: {}
-  """
+            yamlFile 'pipelines/unittests/AgentOracle.yaml'
         }
     }
 
@@ -141,21 +73,21 @@ spec:
                         script: "git diff --name-only HEAD~1 HEAD",
                         returnStdout: true
                         ).trim()
-                        
+
                         echo "Files changed in last commit: ${changedFiles}"
-                        
+
                         // Check if only Jenkinsfile and/or sonarUtils.groovy were changed
                         def filesList = changedFiles.split('\n')
                         def allowedFiles = [
                             "pipelines/unittests/Jenkinsfile",
                             "pipelines/unittests/utils/sonarUtils.groovy"
                         ]
-                        
+
                         // Check if all changed files are in the allowed list
                         def onlyAllowedFiles = filesList.every { file -> 
                             allowedFiles.contains(file)
                         }
-                        
+
                         // Additionally check that at least one of the allowed files was changed
                         def hasAllowedFiles = filesList.any { file -> 
                             allowedFiles.contains(file)
@@ -166,7 +98,7 @@ spec:
                             echo "📋 Changed files: ${changedFiles}"
 
                             sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_SUCCESS_STATUS} \"Pipeline skipped - Only pipeline config files changed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
-                            
+
                             echo "✅ Pipeline execution aborted successfully. Commit marked as success."
                             currentBuild.result = ABORTED
                             return
@@ -175,7 +107,6 @@ spec:
                             echo "📋 Changed files: ${changedFiles}"
                             currentBuild.result = SUCCESS
                         }
-                        
                     } catch (Exception e) {
                         echo "❌ Error in pipeline skip condition check: ${e.getMessage()}"            
                         env.ERROR_MESSAGE = "Pipeline Check Failed"
@@ -220,9 +151,126 @@ spec:
                             env.CATALINA_HOME = "${WORKSPACE}/${TOMCAT_FOLDER}"
                             env.CATALINA_BASE = "${WORKSPACE}/${TOMCAT_FOLDER}"
 
+                            env.STACK_INFO = stackConfig.generateStackMessage()
+                            echo "__________________________________________________"
+                            echo "${env.STACK_INFO}"
+                            echo "__________________________________________________"
+
                             sh "git clone ${REPO_URL} ${REPO_NAME}"
+
+                            env.WORKDIR_ETENDO = "${pwd()}"
+
                             dir(REPO_NAME) {
+                                echo "---------------- Getting Commit Information ----------------"
                                 sh "git checkout ${GIT_COMMIT}"
+                                def infoCommit = load "${rootDir}/pipelines/unittests/utils/infoCommit.groovy"
+                                env.COMMIT_INFO = infoCommit.generateCommitInfo(env.REPO_URL)
+
+                                echo "--------------- Getting Backport Branch Information ---------------"
+                                def pattern = /-Y\d{2}$/
+                                env.CONTAINS_Y_SUFFIX = (env.GIT_BRANCH ==~ pattern) ? TRUE : FALSE
+
+                                // Extract backport branch information without using Matcher object
+                                if (env.CONTAINS_Y_SUFFIX == TRUE) {
+                                    def branchParts = env.GIT_BRANCH.split('-Y')
+                                    if (branchParts.length == 2 && branchParts[1].length() == 4) {
+                                        def yearMonth = branchParts[1]
+                                        def num1 = yearMonth.substring(0, 2)
+                                        def num2 = yearMonth.substring(2, 4)
+                                        env.BACKPORT_BRANCH = "release/${num1}.${num2}.4"
+                                        echo "BACKPORT_BRANCH set to ${env.BACKPORT_BRANCH}"
+                                    } else {
+                                        env.BACKPORT_BRANCH = ""
+                                        echo "No valid backport branch pattern matched."
+                                    }
+                                } else {
+                                    env.BACKPORT_BRANCH = ""
+                                    echo "No backport branch pattern matched."
+                                }
+
+                                if (CLONE_PLUGIN == TRUE) {
+                                    echo "---------------------- Clonning Etendo Plugin Repository ----------------------"
+
+                                    def isFeatureBranch = env.GIT_BRANCH.startsWith("feature/")
+                                    def epicKey = ''
+
+                                    if (isFeatureBranch) {
+                                        echo "-------------------------- Feature Branch Detected --------------------------"
+                                        def taskName = env.GIT_BRANCH.replaceAll("feature/", "").replaceAll("-Y\\d+", "")
+                                        epicKey = sh(script: "bash ${rootDir}/pipelines/unittests/utils/jira-utils.sh ${taskName} ${JIRA_BASE_URL} ${JIRA_ACCESS_TOKEN}", returnStdout: true).trim()
+                                        if (epicKey) {
+                                            echo "Epic Key: ${epicKey}"
+                                            if (env.GIT_BRANCH.contains("-Y")) {
+                                                env.EPIC_BRANCH = "epic/${epicKey}-Y${env.GIT_BRANCH.split('-Y')[1]}"
+                                            } else {
+                                                env.EPIC_BRANCH = "epic/${epicKey}"
+                                            }
+                                            echo "Epic Branch: ${env.EPIC_BRANCH}"
+                                        }
+                                    }
+
+                                    withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
+                                    sh "GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git clone ${PLUGIN_URL} ${PLUGIN_NAME}"
+                                    }
+
+                                    if (!(env.GIT_BRANCH.contains("-Y")) && !(env.GIT_BRANCH.startsWith("release")) && !(env.GIT_BRANCH.startsWith("main" )) && !(env.GIT_BRANCH.startsWith("master")) && !(env.GIT_BRANCH.startsWith("hotfix"))) {
+                                        if (isFeatureBranch && epicKey) {
+                                            sh """
+                                            cd ${PLUGIN_NAME}
+                                            git checkout ${env.EPIC_BRANCH} || git checkout ${env.DEVELOP_BRANCH}
+                                            """
+                                        } else {
+                                            sh """
+                                            cd ${PLUGIN_NAME}
+                                            git checkout ${env.DEVELOP_BRANCH}
+                                            """
+                                        }
+                                    } else if (env.GIT_BRANCH.contains("-Y") || env.GIT_BRANCH.startsWith("release")) {
+                                        if (isFeatureBranch && epicKey) {
+                                            sh """
+                                            cd ${PLUGIN_NAME}
+                                            git checkout ${env.EPIC_BRANCH} || git checkout ${env.BACKPORT_BRANCH}
+                                            """
+                                        } else {
+                                            sh """
+                                            cd ${PLUGIN_NAME}
+                                            git checkout ${env.BACKPORT_BRANCH}
+                                            """
+                                        }
+                                    }
+
+                                    sh """
+                                    cd ${PLUGIN_NAME}
+                                    git checkout ${env.GIT_BRANCH} || echo 'Branch ${env.GIT_BRANCH} not found in Etendo plugin'
+                                    """
+
+                                    echo "--------------- Configure gradle.properties in Etendo plugin folder ---------------"
+                                    sh """
+                                    cd ${PLUGIN_NAME}
+                                    echo "\n
+                                    nexusUser=${NEXUS_USER}
+                                    nexusPassword=${NEXUS_PASSWORD}
+                                    githubUser=${GITHUB_USER}
+                                    githubToken=${GITHUB_TOKEN}
+                                    test.bbdd.url=
+                                    test.bbdd.sid=
+                                    test.bbdd.systemUser=
+                                    test.bbdd.systemPassword=
+                                    test.bbdd.user=
+                                    test.bbdd.password=
+                                    org.gradle.daemon=false
+                                    org.gradle.jvmargs=-Dfile.encoding=UTF-8
+                                    etendoCoreVersion=" > gradle.properties
+                                    """
+
+                                    echo "--------------- Configure build.gradle in Etendo ---------------"
+                                    sh """
+                                    cd ${env.WORKDIR_ETENDO}
+                                    sed -i "s/\\(id 'com.etendoerp.gradleplugin[^']*'\\) version '\\([^']*\\)'/\\1 \\/\\/ version '\\2'/" "\${REPO_NAME}/build.gradle"
+                                    """
+                                }
+
+                                echo "--------------- Configure gradle.properties in Etendo ---------------"
                                 sh """
                                 echo "\n
                                 context.name=${CONTEXT_NAME}\n
@@ -524,7 +572,7 @@ spec:
             script {
                 sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_FAILED_STATUS} \"${env.ERROR_MESSAGE}\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
                 echo "--------------- FAILURE ---------------"
-        
+
                 def rootDir = pwd()
                 def emailNotifier = load "${rootDir}/pipelines/unittests/utils/emailNotifier.groovy"
 
